# Generated by Django 4.2.4 on 2023-08-10 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever', models.CharField(max_length=10)),
                ('cough', models.CharField(max_length=10)),
                ('fatigue', models.CharField(max_length=10)),
                ('difficulty_breathing', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_result', models.CharField(max_length=100)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('health_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='viroShield_App.healthstatus')),
            ],
        ),
        migrations.AddField(
            model_name='healthstatus',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viroShield_App.patient'),
        ),
    ]
